# Generated by Django 3.0.3 on 2020-02-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='currentRoom',
        ),
        migrations.AddField(
            model_name='player',
            name='current_room',
            field=models.CharField(default='DEFAULT CURRENT ROOM', max_length=500),
        ),
        migrations.AddField(
            model_name='player',
            name='title',
            field=models.CharField(default='DEFAULT TITLE', max_length=500),
        ),
    ]
