# Generated by Django 3.0.3 on 2020-02-07 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adventure', '0002_auto_20200207_1014'),
        ('adventure', '0002_auto_20200207_0318'),
    ]

    operations = [
    ]
